name: lux_watch_rol
description: A luxury watch shopping app for enthusiasts.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true